name: langpal_prototype
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  country_flags: ^1.0.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  supabase_flutter: ^2.3.0
  html: ^0.15.6
  audioplayers: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
  flutter_lints: ^5.0.0
  flutter_app_name: ^0.1.1
  xml: ^5.1.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/langpal_logos/LangPal-Primary-mascot.png"

flutter_app_name:
  name: "LangPal"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/flags/
    - assets/langpal_logos/
    - assets/social_logos/
    - assets/audio/games/
  #   - images/a_dot_ham.jpeg

